source: server.purs
engineUrl: http://localhost:9000
imports:
  getUser:
    uri: https://api.github.com/users{/user}/repos
    response: | 
      Prim.Array
        { id :: Prim.Int
        , name :: Prim.String
        , stargazers_count :: Prim.Int
        }
tables:
  albums:
    columns:
      - name: id
        type: number
      - name: title
        type: string
      - name: artist_id
        type: number
  artists:
    columns:
      - name: id
        type: number
      - name: name
        type: string
  tracks:
    columns:
      - name: album_id
        type: number
      - name: bytes
        type: number
      - name: composer
        type: string
        nullable: true
      - name: genre_id
        type: number
      - name: id
        type: number
      - name: media_type_id
        type: number
      - name: milliseconds
        type: number
      - name: name
        type: string
      - name: unit_price
        type: number 