source: server.purs
engineUrl: http://localhost:9000
imports:
  getUser:
    uri: https://api.github.com/users{/user}/repos
    response: | 
      Prim.Array
        { id :: Prim.Int
        , name :: Prim.String
        , stargazers_count :: Prim.Int
        }
tables:
  albums:
    columns:
      - name: id
        dataType: number
      - name: title
        dataType: string
      - name: artist_id
        dataType: number
  artists:
    columns:
      - name: id
        dataType: number
      - name: name
        dataType: string
  tracks:
    columns:
      - name: album_id
        dataType: number
      - name: bytes
        dataType: number
      - name: composer
        dataType: string
      - name: genre_id
        dataType: number
      - name: id
        dataType: number
      - name: media_type_id
        dataType: number
      - name: milliseconds
        dataType: number
      - name: name
        dataType: string
      - name: unit_price
        dataType: number 